# Secrets Manager entries. Terraform creates the entry shells; the actual
# secret values are populated out-of-band so they never enter the state file.
#
# Populate after `terraform apply` with, e.g.:
#   aws secretsmanager put-secret-value \
#     --secret-id <name> --secret-string "<value>"

locals {
  provider_secret_names = [
    "twilio-api-key-sid",
    "twilio-api-key-secret",
    "gemini-api-key", # covers STT + LLM
    "gradium-api-key",
  ]
}

resource "aws_secretsmanager_secret" "provider" {
  for_each = toset(local.provider_secret_names)
  name     = "${local.name_prefix}-${each.key}"
}

# RDS password is generated by Terraform, so we *do* store it (encrypted by
# Secrets Manager). The app reads DATABASE_URL from a derived secret to keep
# the password out of the task definition's plaintext env.
resource "aws_secretsmanager_secret" "db_url" {
  name = "${local.name_prefix}-database-url"
}

resource "aws_secretsmanager_secret_version" "db_url" {
  secret_id = aws_secretsmanager_secret.db_url.id
  secret_string = format(
    "postgresql+asyncpg://%s:%s@%s:%d/%s",
    var.db_username,
    random_password.db_password.result,
    aws_db_instance.main.address,
    aws_db_instance.main.port,
    aws_db_instance.main.db_name,
  )
}

resource "aws_secretsmanager_secret" "redis_url" {
  name = "${local.name_prefix}-redis-url"
}

resource "aws_secretsmanager_secret_version" "redis_url" {
  secret_id     = aws_secretsmanager_secret.redis_url.id
  secret_string = "redis://${aws_elasticache_cluster.main.cache_nodes[0].address}:6379/0"
}
